# Generated by Django 2.2.1 on 2019-05-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pwd',
            field=models.CharField(default='some string', max_length=8),
            preserve_default=False,
        ),
    ]
