# Generated by Django 2.2.1 on 2019-06-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_pwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pwd',
            new_name='who',
        ),
    ]
